### ISSUE TITLE
List of SMT modulo theories? Can synthesis handle all?

### ISSUE THREAD

**Issue by HanzhengLi** [nadia-polikarpova/cse291-program-synthesis#4]
How many SMT modulo theories are there and what are their names? Which of them can be handled by the current synthesis techniques?
After reading EUSolver, I'm just kind of curious about this. Because the paper describes its method with examples in a subset of Linear Integer Arithmetic only. And I feel like such kind of enumeration-based techniques will not work on large-size or infinite theories, like float-point numbers and real numbers, right? Besides, I cannot see that this framework will support loops or recursions, yet we've seen recursion in 
the program synthesized by Synquid in class. Therefore, I'm curious about which SMT modulo theory includes recursions, and about how well current synthesis techniques handle them.

**Comment by nadia-polikarpova** [comment]
I think you're asking about two separate things: 1) Which theories are supported by SMT solvers? and 2) What kinds of programs can be handled by which synthesis techniques/tool?

1) Theories commonly supported by SMT solvers are Linear Integer Arithmetic, Real Arithmetic, Uninterpreted Functions, Bit Vectors, Arrays, Algebraic Data Types. A good intro into what SMT solvers can do for you is this [Z3 tutorial](https://rise4fun.com/Z3/tutorial). We will look at SMT solvers in more detail later in class, but a short answer is that, yes, SMT solvers can handle real numbers. [Sean Gao](https://scungao.github.io/)'s solver [dREal](http://dreal.github.io/) is particularly good at it and can even handle transcendental functions!

2) The main problem with synthesizing programs with loop or recursion is that they are hard to verify (i.e. check that the program satisfies the specification). In EUSolver, since the programs are in conditional LIA, it is really easy to translate this program into a logical formula that an SMT solver can understand (basically, the program *is* the formula). With loops/recursion you need a more sophisticated translation, e.g. involving loop invariants. We will look at this later in the class.

**Comment by HanzhengLi** [comment]
That would be helpful, thanks!
